
const AccessModule = {
  USER_ACCESS: 100,
  ENDUSER_ACCESS: 110,
  NOTIFICATION_ACCESS: 120,
  ATTENDANCE_ACCESS: 130,
  LESSON_ACCESS: 140,
  STAFF_ACCESS: 150,
  FINANCE_ACCESS: 160,
  ORGANIZATION_ACCESS: 170
};
export default AccessModule;